# docker-compose for development stack
version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
        POSTGRES_PASSWORD: mydbsecretpwd
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
        - dbdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 3000:8080

  migrate:
    build: .
    image: authcompanion
    env_file:
      - .env
    depends_on:
        db:
          condition: service_healthy
    command: ./migrate.linux-amd64 -source file://db/migrations -database "postgres://$DBUSER:$DBPASSWORD@$DBHOSTNAME:$DBPORT/$DATABASE?sslmode=disable" up

  api:
    build: .
    env_file:
      - .env
    image: authcompanion
    restart: always
    depends_on:
      - migrate
    volumes:
      - ./:/app
    ports:
      - 127.0.0.1:3002:3002

volumes:
     dbdata:
